### ISSUE TITLE
Problem of reproducing the results

### ISSUE THREAD

**Issue by felixgwu** [SimJeg/FC-DenseNet#11]
Hi, 

I was impressed by your excellent work and tried implement a PyTorch version of it.
Unfortunately, I have trouble when reproducing your results.

I followed the setting as follows:
- Using FC-DenseNet-103
- Using RMSprop with initial learning rate: 1e-3, decay rate: 0.995, weight decay: 1e-4,
- Pretrain the model with randomly cropping to 224x224 and fine-tune it with the original size
- Using patience = 100 for pretraining and 50 for fine-tuning. The maximum number of epoch is set to 750 as in this code.
- Dropout rate = 0.2
- Since there is no preprocessing code in this repository, I tried either normalize the images or not.

I found that without dropout the model learns much better than the one with the one with dropout.
However, none of these settings can get the same accuracy as what reported in the paper.
The validation accuracy is 0.9372 and the mIoU is 0.7025; however, the test accuracy is only 0.8932 and the test mIoU is 0.5790.

I am wondering what is the data preprocessing method you used.
Is there anything wrong with my experiment procedure?

Also, I tried to run your code with my implementation of dataloader (following your explanation of data format).
However I got `RuntimeError: error getting worksize: CUDNN_STATUS_BAD_PARAM` 
It suggested me use 'optimizer=None', but it took me more than 3 hours to compile the model before I killed the job.
FYI, I used the latest theano and lasagne with CUDA 8.0 and CUDNN 5.1. 
Do I have to use a different version?

Thanks in advance.

**Comment by SimJeg** [comment]
Hi, thank you for your feedback. Please refer to the PR #10 
You must use fast_compile to be able to compile the model and optimizer_including=fusion to enable an important optimization for a speedup during training
