### ISSUE TITLE
How long does it take to compile FC-Densenet103?

### ISSUE THREAD

**Issue by jrao1** [SimJeg/FC-DenseNet#4]
I'm running this on an i7 and it has been running for 48 hours, still not finished. Has anyone successfully compiled it? I'm using latest Theano with libgpuarray backend.

**Comment by SimJeg** [comment]
Hi, as described in the README, compilation should take less than 10 minutes on a GPU. 
Do you use the following flags ? 
THEANO_FLAGS='device=cuda,optimizer=fast_compile,optimizer_including=fusion'

**Comment by jrao1** [comment]
Sorry, you're right, the flags solved the problem, I didn't realize the difference between fast_run and fast_compile is so huge.
